// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Global = require("../Global.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var InputStd = require("../Widgets/InputStd.bs.js");
var ButtonStd = require("../Widgets/ButtonStd.bs.js");

function ContentTableSeating(Props) {
  var dispatch = Props.dispatch;
  var state = Props.state;
  return React.createElement(React.Fragment, undefined, React.createElement(InputStd.make, {
                  id: "identity"
                }), React.createElement(InputStd.make, {
                  id: "name"
                }), React.createElement(ButtonStd.make, {
                  state: state,
                  label: "Join",
                  id: "connect"
                }), React.createElement(ButtonStd.make, {
                  state: state,
                  label: "Leave",
                  id: "disconnect"
                }), React.createElement("div", undefined, "Hello Table Seating"), React.createElement("table", {
                  style: {
                    border: "0px solid black",
                    borderCollapse: "collapse",
                    margin: "auto"
                  }
                }, React.createElement("thead", undefined), React.createElement("tbody", undefined, React.createElement("tr", {
                          style: {
                            backgroundColor: "#f8f8f8",
                            color: "#000000"
                          }
                        }, React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  state: state,
                                  label: "N",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  state: state,
                                  label: "E",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  state: state,
                                  label: "S",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  state: state,
                                  label: "W",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  state: state,
                                  label: "X",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  state: state,
                                  label: "Y",
                                  id: "x"
                                })), React.createElement("td", {
                              style: {
                                border: "0px solid red",
                                borderCollapse: "collapse",
                                margin: "0vh",
                                padding: "0vh 0vh 0vh 0vh"
                              }
                            }, React.createElement(ButtonStd.make, {
                                  state: state,
                                  label: "Z",
                                  id: "x"
                                }))))), React.createElement("button", {
                  id: "addremoteparticipantsid",
                  style: {
                    display: "show"
                  },
                  onClick: (function (param) {
                      return Curry._1(dispatch, {
                                  TAG: /* AddRemoteParticipantSid */1,
                                  _0: window.remoteparticipantid
                                });
                    })
                }, "Add"), React.createElement("button", {
                  id: "resizecomponents",
                  style: {
                    display: "none"
                  },
                  onClick: (function (param) {
                      return Curry._1(dispatch, {
                                  TAG: /* ResizeComponents */0,
                                  _0: Global.innerHeightRef.contents,
                                  _1: Global.isLandscapeRef.contents
                                });
                    })
                }, "Res"), React.createElement("button", {
                  id: "removeremoteparticipantsid",
                  style: {
                    display: "show"
                  },
                  onClick: (function (param) {
                      return Curry._1(dispatch, {
                                  TAG: /* RemoveRemoteParticipantSid */2,
                                  _0: window.remoteparticipantid
                                });
                    })
                }, "Rem"), React.createElement("button", {
                  id: "testchangeofgamestate",
                  style: {
                    display: "show"
                  },
                  onClick: (function (param) {
                      return Curry._1(dispatch, {
                                  TAG: /* TestChangeOfGameState */3,
                                  _0: 1
                                });
                    })
                }, "ChangeGameState"), React.createElement("button", {
                  id: "replacegamestatefromremote",
                  style: {
                    display: "show"
                  },
                  onClick: (function (param) {
                      if (Caml_obj.caml_equal(window.receivedGameState, state.game)) {
                        console.log("recd state = local state - action aborted");
                        return ;
                      } else {
                        return Curry._1(dispatch, {
                                    TAG: /* ReplaceGameStateFromRemote */4,
                                    _0: window.receivedGameState
                                  });
                      }
                    })
                }, "ReplaceGameStateFromRemote"));
}

var make = ContentTableSeating;

exports.make = make;
/* react Not a pure module */
