// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var VideoStd = require("../Widgets/VideoStd.bs.js");

function ContentVideo(Props) {
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  id: "participants"
                }, React.createElement("div", {
                      className: "participant",
                      id: "local-participant"
                    }, React.createElement(VideoStd.make, {}))));
}

var make = ContentVideo;

exports.make = make;
/* react Not a pure module */
