// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function getPercentageInnerHeightAsPxString(percentAsFloat, innerHeight) {
  return (percentAsFloat * innerHeight / 100.0).toFixed(0) + "px";
}

exports.getPercentageInnerHeightAsPxString = getPercentageInnerHeightAsPxString;
/* No side effect */
