// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ute = require("../Modules/Ute.bs.js");
var React = require("react");
var ContentTableSeating = require("../RegionsContent/ContentTableSeating.bs.js");

function RegionTableSeating(Props) {
  var dispatch = Props.dispatch;
  var state = Props.state;
  var style = {
    background: "#f8f8f8",
    bottom: state.localDevice.isLandscape ? "60%" : "100vw",
    color: "gray",
    left: state.localDevice.isLandscape ? Ute.getPercentageInnerHeightAsPxString(100.0, state.localDevice.innerHeight) : "54%",
    overflowY: "auto",
    position: "fixed",
    right: "0",
    textAlign: "center",
    top: "0"
  };
  return React.createElement("div", {
              style: style
            }, React.createElement(ContentTableSeating.make, {
                  dispatch: dispatch,
                  state: state
                }));
}

var make = RegionTableSeating;

exports.make = make;
/* react Not a pure module */
