// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ute = require("../Modules/Ute.bs.js");
var React = require("react");
var ContentScoreSheet = require("../RegionsContent/ContentScoreSheet.bs.js");

function RegionScoreSheet(Props) {
  var state = Props.state;
  var style = {
    background: "#e0e0e0",
    bottom: state.localDevice.isLandscape ? "0" : "100vw",
    color: "gray",
    left: state.localDevice.isLandscape ? Ute.getPercentageInnerHeightAsPxString(100.0, state.localDevice.innerHeight) : "0",
    overflowY: "auto",
    position: "fixed",
    right: state.localDevice.isLandscape ? "0" : "55%",
    textAlign: "center",
    top: state.localDevice.isLandscape ? "50%" : "0"
  };
  return React.createElement("div", {
              id: "regionscoresheet",
              style: style
            }, React.createElement(ContentScoreSheet.make, {
                  state: state
                }));
}

var make = RegionScoreSheet;

exports.make = make;
/* react Not a pure module */
