// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ute = require("../Modules/Ute.bs.js");
var React = require("react");
var ContentVideo = require("../RegionsContent/ContentVideo.bs.js");

function RegionVideo(Props) {
  var state = Props.state;
  var style = {
    background: "#e0e0f0",
    bottom: state.isLandscape ? "50%" : "100vw",
    color: "gray",
    left: state.isLandscape ? Ute.getPercentageInnerHeightAsPxString(100.0, state.innerHeight) : "0",
    overflowY: "auto",
    position: "fixed",
    right: state.isLandscape ? "0" : "46%",
    textAlign: "center",
    top: state.isLandscape ? "40%" : "0"
  };
  return React.createElement("div", {
              style: style
            }, React.createElement(ContentVideo.make, {
                  state: state
                }));
}

var make = RegionVideo;

exports.make = make;
/* react Not a pure module */
