// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ute = require("../Modules/Ute.bs.js");
var React = require("react");

function getStyle(state) {
  if (state.isLandscape) {
    return {
            backgroundColor: "#003500",
            backgroundImage: "url(./assets/green_baize.jpg)",
            height: Ute.getPercentageInnerHeightAsPxString(100.0, state.innerHeight),
            left: "0",
            position: "fixed",
            top: "0",
            width: Ute.getPercentageInnerHeightAsPxString(100.0, state.innerHeight),
            backgroundSize: "cover"
          };
  } else {
    return {
            backgroundColor: "#003500",
            backgroundImage: "url(./assets/green_baize.jpg)",
            bottom: "0",
            height: "100vw",
            left: "0",
            position: "fixed",
            width: "100vw",
            backgroundSize: "cover"
          };
  }
}

function RegionCardTable(Props) {
  var state = Props.state;
  var style = getStyle(state);
  return React.createElement("div", {
              style: style
            }, null);
}

var make = RegionCardTable;

exports.getStyle = getStyle;
exports.make = make;
/* react Not a pure module */
