// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Global = require("./Global.bs.js");
var RegionCardTable = require("./RegionsStyling/RegionCardTable.bs.js");

function App(Props) {
  var match = React.useReducer(Global.reducer, Global.initialState);
  var dispatch = match[1];
  var state = match[0];
  return React.createElement(React.Fragment, undefined, "state.innerHeight:" + String(state.innerHeight), "state.isLandscape:" + String(state.isLandscape), React.createElement("div", {
                  id: "resizecomponents",
                  style: {
                    display: "none"
                  },
                  onClick: (function (param) {
                      return Curry._1(dispatch, {
                                  TAG: /* ResizeComponents */2,
                                  _0: Global.innerHeightRef.contents,
                                  _1: Global.isLandscapeRef.contents
                                });
                    })
                }), React.createElement(RegionCardTable.make, {
                  state: state
                }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
