// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Global = require("./Global.bs.js");
var RegionVideo = require("./RegionsStyling/RegionVideo.bs.js");
var RegionTableSeating = require("./RegionsStyling/RegionTableSeating.bs.js");

function App(Props) {
  var match = React.useReducer(Global.reducer, Global.initialState);
  var state = match[0];
  ((window.localDataTrack == undefined 
      ?
      console.log('skip on lDT undefined')
      :
      window.localDataTrack.send(JSON.stringify(state.game))));
  console.log("new state: ", state);
  return React.createElement(React.Fragment, undefined, React.createElement(RegionVideo.make, {
                  state: state
                }), React.createElement(RegionTableSeating.make, {
                  dispatch: match[1],
                  state: state
                }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
