// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var React = require("react");
var Global = require("./Global.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var RegionVideo = require("./RegionsStyling/RegionVideo.bs.js");
var RegionTableSeating = require("./RegionsStyling/RegionTableSeating.bs.js");

function App(Props) {
  var match = React.useReducer(Global.reducer, Global.initialState);
  var dispatch = match[1];
  var state = match[0];
  window.gameState = state.game;
  console.log("new game state: ", state.game);
  //console.log("snuck in");
  if (window.localDataTrack == undefined) {
    console.log('skip on lDT undefined')
  } else {
    window.localDataTrack.send(JSON.stringify(state.game));
  }
  //console.log("snuck out");
  return React.createElement(React.Fragment, undefined, React.createElement("button", {
    id: "resizecomponents",
    style: {
      display: "none"
    },
    onClick: (function (param) {
      return Curry._1(dispatch, {
        TAG: /* ResizeComponents */0,
        _0: Global.innerHeightRef.contents,
        _1: Global.isLandscapeRef.contents
      });
    })
  }, "Res"), React.createElement("button", {
    id: "addremoteparticipantsid",
    style: {
      display: "show"
    },
    onClick: (function (param) {
      return Curry._1(dispatch, {
        TAG: /* AddRemoteParticipantSid */1,
        _0: window.remoteparticipantid
      });
    })
  }, "Add"), React.createElement("button", {
    id: "removeremoteparticipantsid",
    style: {
      display: "show"
    },
    onClick: (function (param) {
      return Curry._1(dispatch, {
        TAG: /* RemoveRemoteParticipantSid */2,
        _0: window.remoteparticipantid
      });
    })
  }, "Rem"), React.createElement("button", {
    id: "testchangeofgamestate",
    style: {
      display: "show"
    },
    onClick: (function (param) {
      return Curry._1(dispatch, {
        TAG: /* TestChangeOfGameState */3,
        _0: 1
      });
    })
  }, "ChangeGameState"), React.createElement("button", {
    id: "replacegamestatefromremote",
    style: {
      display: "show"
    },
    onClick: (function (param) {
      if (Caml_obj.caml_equal(window.receivedGameState, state.game)) {
        console.log("recd state = local state - action aborted");
        return;
      } else {
        return Curry._1(dispatch, {
          TAG: /* ReplaceGameStateFromRemote */4,
          _0: window.receivedGameState
        });
      }
    })
  }, "ReplaceGameStateFromRemote"), React.createElement(RegionVideo.make, {
    state: state
  }), React.createElement(RegionTableSeating.make, {
    state: state
  }));
}

var make = App;

exports.make = make;
/* react Not a pure module */
