// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");

var innerHeightRef = {
  contents: 0
};

var isLandscapeRef = {
  contents: true
};

function updateUIStateOnLoadOrResize(param) {
  innerHeightRef.contents = window.innerHeight;
  isLandscapeRef.contents = Caml_obj.caml_lessthan(window.innerHeight, window.innerWidth);
  console.log("innerHeight: " + String(innerHeightRef.contents) + " isLandscape: " + String(isLandscapeRef.contents));
  ((document.getElementById("resizecomponents").click()));
  
}

Curry._2(window.addEventListener, "resize", (function (_event) {
        console.log("event window resize..");
        return updateUIStateOnLoadOrResize(undefined);
      }));

Curry._2(window.addEventListener, "load", (function (_event) {
        console.log("event window load..");
        return updateUIStateOnLoadOrResize(undefined);
      }));

function reducer(state, action) {
  if (typeof action === "number") {
    switch (action) {
      case /* Inc */0 :
          return {
                  innerHeight: state.innerHeight + 1 | 0,
                  isLandscape: state.isLandscape
                };
      case /* Dec */1 :
          return {
                  innerHeight: state.innerHeight - 1 | 0,
                  isLandscape: state.isLandscape
                };
      case /* Reset */2 :
          return {
                  innerHeight: 0,
                  isLandscape: state.isLandscape
                };
      
    }
  } else {
    switch (action.TAG | 0) {
      case /* MultByN */0 :
          return {
                  innerHeight: Math.imul(state.innerHeight, action._0),
                  isLandscape: state.isLandscape
                };
      case /* MultByNM */1 :
          return {
                  innerHeight: Math.imul(Math.imul(state.innerHeight, action._0), action._1),
                  isLandscape: state.isLandscape
                };
      case /* ResizeComponents */2 :
          return {
                  innerHeight: action._0,
                  isLandscape: action._1
                };
      
    }
  }
}

var initialState = {
  innerHeight: 0,
  isLandscape: true
};

exports.innerHeightRef = innerHeightRef;
exports.isLandscapeRef = isLandscapeRef;
exports.updateUIStateOnLoadOrResize = updateUIStateOnLoadOrResize;
exports.initialState = initialState;
exports.reducer = reducer;
/*  Not a pure module */
