// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ute = require("../Modules/Ute.bs.js");
var React = require("react");

function VideoStd(Props) {
  var state = Props.state;
  var style = {
    height: state.localDevice.isLandscape ? Ute.getPercentageInnerHeightAsPxString(10.0, state.localDevice.innerHeight) : Ute.getPercentageInnerHeightAsPxString(10.0, window.innerWidth),
    overflow: "hidden",
    width: state.localDevice.isLandscape ? Ute.getPercentageInnerHeightAsPxString(10.0, state.localDevice.innerHeight) : Ute.getPercentageInnerHeightAsPxString(10.0, window.innerWidth),
    borderRadius: "20%",
    objectFit: "cover"
  };
  return React.createElement("video", {
              style: style
            });
}

var make = VideoStd;

exports.make = make;
/* react Not a pure module */
