// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function VideoStd(Props) {
  var style = {
    height: "10vh",
    overflow: "hidden",
    width: "10vh",
    borderRadius: "20%",
    objectFit: "cover"
  };
  return React.createElement("video", {
              style: style
            });
}

var make = VideoStd;

exports.make = make;
/* react Not a pure module */
