// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Ute = require("../Modules/Ute.bs.js");
var React = require("react");

function VideoStd(Props) {
  var state = Props.state;
  var style = {
    backgroundColor: "red",
    height: Ute.getPercentageInnerHeightAsPxString(10.0, state.innerHeight),
    overflow: "hidden",
    width: Ute.getPercentageInnerHeightAsPxString(10.0, state.innerHeight),
    borderRadius: "20%",
    objectFit: "cover"
  };
  return React.createElement("video", {
              style: style
            });
}

var make = VideoStd;

exports.make = make;
/* react Not a pure module */
